name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    container: jackpar/x11-zig:0.16.0-dev.2963

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: zig build

      - name: Test project
        run: zig build test --summary all
