name: Build

on:
  push:
    branches: [ yt ]
  pull_request:
    branches: [ yt ]

  jobs:
    build:
      runs-on: blacksmith-4vcpu-ubuntu-2404
      container: jackpar/x11-zig:0.16.0-dev.2962

    steps:
      - name: Checkout version
        uses: actions/checkout@v4

      - name: Lint project
        run: zig fmt --check .

      - name: Test project
        run: zig build test
